/'
# Terminology in next generation credentials

Created: 2024/05/24 08:16:45
Last modified: 2024/05/24 12:34:14

For citations and other documentation, please see 
[Zotero group library](https://www.zotero.org/groups/5541646/nextgencredentials)

'/
@startuml 1EdTechTaxon


!include W3CTaxon.puml!0
!include style.puml

Title: NGC from 1EdTech Consortium

!startsub Core
class "Comprehensive Learner Record (CLR)" <<taxStandard>>
"Comprehensive Learner Record (CLR)" --|> "Verifiable credentials (W3C)"
class "Open Badges" <<taxStandard>>
"Open Badges" --|> "Verifiable credentials (W3C)"
class "1EdTech Consortium" <<taxOrg>>
"1EdTech Consortium" ..> "Comprehensive Learner Record (CLR)": maintains
"1EdTech Consortium" ..> "Open Badges": maintains
!endsub

' The microcredential standard seems more esoteric

class "TrustEd Microcredential Framework" <<taxStandard>>
"TrustEd Microcredential Framework" --|> "Open Badges"
class "TrustEd Microcredential Knowledge" <<taxStandard>>
class "TrustEd Microcredential Application" <<taxStandard>>
"TrustEd Microcredential Knowledge" --* "TrustEd Microcredential Framework" : defined in
"TrustEd Microcredential Application" --* "TrustEd Microcredential Framework" : defined in

class "TrustEd Microcredential Coalition" <<taxOrg>>
"1EdTech Consortium"  ..> "TrustEd Microcredential Coalition": coordinates
"TrustEd Microcredential Coalition"  ..> "TrustEd Microcredential Framework" : maintains
!include ./Version.puml
note as source
    R. Coyle, “Clarifying Credentials: What’s the Difference Between CLRs, LERs and Wallets? 
    | 1EdTech.” Accessed: May 22, 2024. [Online]. Available: 
    [[https://www.1edtech.org/blog/clarifying-credentials-whats-the-difference-between-clrs-lers-and-wallets]]
end note

@enduml
