/'
# Terminology in next generation credentials

Created: 2024/05/24 08:16:45
Last modified: 2024/05/24 12:17:16

For citations and other documentation, please see 
[Zotero group library](https://www.zotero.org/groups/5541646/nextgencredentials)
'/
@startuml W3CTaxon-base
!include style.puml

Title: W3C taxonomy

class "Verifiable credentials (W3C)" <<taxStandard>> 
class "W3C" <<taxOrg>>
"W3C" ..> "Verifiable credentials (W3C)": maintains

!include ./Version.puml
@enduml


