/'
# Terminology in next generation credentials

Created: 2024/05/24 08:16:45
Last modified: 2024/06/21 15:38:37

For citations and other documentation, please see 
[Zotero group library](https://www.zotero.org/groups/5541646/nextgencredentials)

Reminder:
    !includesub W3CTaxon-FedCM.puml!FedIDstandards
'/
@startuml W3CTaxonFedCM
    !include style.puml

    Title: W3C and the FedCM community

    !startsub Core
        !include ./fragmentW3C.puml

    !endsub 

    !startsub CredMan
        class "Credential Management" <<taxStandard>>{
            [[https://www.w3.org/TR/credential-management-1/ CM at W3C]]
        }
        "W3C" ..> "Credential Management"  : maintains

    !endsub 

    !startsub FedID
        class "Federated Identity WG" <<taxOrg>>{
            [[https://www.w3.org/groups/wg/fedid/ Working group]]
        }
        "W3C" ..> "Federated Identity WG" : coordinates

        class "Federated Identity CG" <<taxOrg>>{
            [[https://www.w3.org/groups/cg/fed-id/ Community group]]
        }
        "W3C" ..> "Federated Identity CG" : coordinates
        "Federated Identity WG" ..> "Federated Identity CG" : coordinates

        class "Web Platform Incubator CG" <<taxOrg>>{
            [[https://www.w3.org/community/wicg/ Community group]]
        }
        "W3C" ..> "Web Platform Incubator CG" : coordinates

        note as wgFedid450
            [[https://github.com/w3c/strategy/issues/450 issue 450]]
            Adding Digital 
            Credentials to 
            the FedID WG
        end note

       "Federated Identity WG" --  wgFedid450
       wgFedid450 --  "Digital Credentials" 
 
    !endsub
    !startsub FedIDstandards
        class "Digital Credentials" <<taxWork>>{
            [[https://github.com/WICG/digital-credentials/ DC at GitHub]]
        }

       /' Digital Credentials builds upon Credential Management to enable the 
        secure and private exchange of digital identity information. It 
        facilitates authenticated interactions by representing digital 
        credentials through the DigitalIdentity interface, which embodies 
        verifiable claims about an individual's identity.'/

    !endsub
    !startsub FedIDlinks
        "Web Platform Incubator CG"  ..> "Digital Credentials" : incubates
        "Digital Credentials" --|> "Credential Management" 

    !endsub  

    !include ./Version.puml
@enduml


