# Terminology in next generation credentials

Created: 2024/05/24 08:16:45
Last modified: 2024/05/24 18:53:46

For citations and other documentation, please see 
[Zotero group library](https://www.zotero.org/groups/5541646/nextgencredentials)

@startuml sprawlingTaxonomy
    !include ./terminology/style.puml
    !includesub ./terminology/W3CTaxon-VC.puml!Core
    !includesub ./terminology/W3CTaxon-VC.puml!EOCred
    !includesub ./terminology/W3CTaxon-VC.puml!VC
    !includesub ./terminology/W3CTaxon-VC.puml!Cred
    !includesub ./terminology/1EdTechTaxon.puml!Core
    'Simplify by not showing class details 
    hide members
    hide circle

    Title: All the things

    !include ./terminology/Version.puml
@enduml